const LoginMainPageString = {
  Assamese: {
    GetYourGroceries: 'আমাৰ লগত আপোনাৰ গেলামালৰ বস্তু লৈ যাওক',
    ContinuePhone: 'Phone ৰ সৈতে আগবাঢ়ি যাওক',
    ContinueGoogle: 'গুগলৰ সৈতে আগবাঢ়ি যাওক',
    ContinueApple: 'এপলৰ সৈতে আগবাঢ়ি যাওক',
    ErrorGoogleVerifyAccount: 'আপোনাৰ Google একাউণ্ট পৰীক্ষা কৰক',
    ErrorSignInProgress: 'চাইন ইন অগ্ৰগতি হৈছে....',
    ErrorGooglePlayServices: 'Google Play সেৱাসমূহ উপলব্ধ নহয়',
    ErrorCancelledSignInFlow: "গুগল চাইন ইন ফ্ল' বাতিল কৰা হৈছে",
  },
  Bengali: {
    GetYourGroceries: 'আমাদের সাথে আপনার মুদি পান',
    ContinuePhone: 'ফোন দিয়ে চালিয়ে যান',
    ContinueGoogle: 'Google এর সাথে চালিয়ে যান',
    ContinueApple: 'অ্যাপলের সাথে চালিয়ে যান',
    ErrorGoogleVerifyAccount: 'আপনার Google অ্যাকাউন্ট যাচাই করুন',
    ErrorSignInProgress: 'সাইন ইন চলছে.....',
    ErrorGooglePlayServices: 'Google Play পরিষেবাগুলি উপলব্ধ নেই৷',
    ErrorCancelledSignInFlow: 'Google সাইন ইন ফ্লো বাতিল হয়েছে',
  },
  Bodo: {
    GetYourGroceries: 'আমাদের সাথে আপনার মুদি পান',
    ContinuePhone: 'ফোন দিয়ে চালিয়ে যান',
    ContinueGoogle: 'Google এর সাথে চালিয়ে যান',
    ContinueApple: 'অ্যাপলের সাথে চালিয়ে যান',
    ErrorGoogleVerifyAccount: 'আপনার Google অ্যাকাউন্ট যাচাই করুন',
    ErrorSignInProgress: 'সাইন ইন চলছে.....',
    ErrorGooglePlayServices: 'Google Play পরিষেবাগুলি উপলব্ধ নেই৷',
    ErrorCancelledSignInFlow: 'Google সাইন ইন ফ্লো বাতিল হয়েছে',
  },
  Dogri: {
    GetYourGroceries: 'अपने किराने दा सामान साढ़े कन्ने लेई आओ',
    ContinuePhone: 'फोन दे नाल जारी रखो',
    ContinueGoogle: 'गूगल दे कन्नै जारी रक्खो',
    ContinueApple: 'एप्पल दे कन्नै जारी रक्खो',
    ErrorGoogleVerifyAccount: 'अपने गूगल खाते दी सत्यापन करो',
    ErrorSignInProgress: 'साइन इन प्रगति करदा ऐ.....',
    ErrorGooglePlayServices: 'गूगल प्ले सेवाएं उपलब्ध नेईं न',
    ErrorCancelledSignInFlow: 'गूगल साइन इन प्रवाह रद्द कीता गेआ',
  },
  English: {
    GetYourGroceries: 'Get your groceries with us',
    ContinuePhone: 'Continue with Phone',
    ContinueGoogle: 'Continue with Google',
    ContinueApple: 'Continue with Apple',
    ErrorGoogleVerifyAccount: 'Verify your Google Account',
    ErrorSignInProgress: 'Sign in is progressing.....',
    ErrorGooglePlayServices: 'Google Play Services are not available',
    ErrorCancelledSignInFlow: 'Cancelled the Google Sign In Flow',
  },
  Gujrati: {
    GetYourGroceries: 'તમારી કરિયાણા અમારી સાથે મેળવો',
    ContinuePhone: 'ફોન સાથે ચાલુ રાખો',
    ContinueGoogle: 'Google સાથે ચાલુ રાખો',
    ContinueApple: 'Apple સાથે ચાલુ રાખો',
    ErrorGoogleVerifyAccount: 'તમારું Google એકાઉન્ટ ચકાસો',
    ErrorSignInProgress: 'સાઇન ઇન ચાલુ છે.....',
    ErrorGooglePlayServices: 'Google Play સેવાઓ ઉપલબ્ધ નથી',
    ErrorCancelledSignInFlow: 'Google સાઇન ઇન ફ્લો રદ કર્યો',
  },
  Hindi: {
    GetYourGroceries: 'अपने किराने का सामान हमारे साथ प्राप्त करें',
    ContinuePhone: 'फ़ोन के साथ जारी रखें',
    ContinueGoogle: 'Google के साथ जारी रखें',
    ContinueApple: 'सेब के साथ जारी रखें',
    ErrorGoogleVerifyAccount: 'अपना Google खाता सत्यापित करें',
    ErrorSignInProgress: 'साइन इन प्रगति पर है.....',
    ErrorGooglePlayServices: 'Google Play सेवाएं उपलब्ध नहीं हैं',
    ErrorCancelledSignInFlow: 'Google साइन इन फ़्लो रद्द',
  },
  Kannada: {
    GetYourGroceries: 'ನಿಮ್ಮ ದಿನಸಿ ಸಾಮಾನುಗಳನ್ನು ನಮ್ಮೊಂದಿಗೆ ಪಡೆಯಿರಿ',
    ContinuePhone: 'ಫೋನ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ContinueGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    ContinueApple: 'Apple ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ErrorGoogleVerifyAccount: 'ನಿಮ್ಮ Google ಖಾತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    ErrorSignInProgress: 'ಸೈನ್ ಇನ್ ಪ್ರಗತಿಯಲ್ಲಿದೆ.....',
    ErrorGooglePlayServices: 'Google Play ಸೇವೆಗಳು ಲಭ್ಯವಿಲ್ಲ',
    ErrorCancelledSignInFlow: 'Google ಸೈನ್ ಇನ್ ಫ್ಲೋ ಅನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
  },
  Kashmiri: {
    GetYourGroceries: 'अपने किराने का सामान हमारे साथ प्राप्त करें',
    ContinuePhone: 'फ़ोन के साथ जारी रखें',
    ContinueGoogle: 'Google के साथ जारी रखें',
    ContinueApple: 'सेब के साथ जारी रखें',
    ErrorGoogleVerifyAccount: 'अपना Google खाता सत्यापित करें',
    ErrorSignInProgress: 'साइन इन प्रगति पर है.....',
    ErrorGooglePlayServices: 'Google Play सेवाएं उपलब्ध नहीं हैं',
    ErrorCancelledSignInFlow: 'Google साइन इन फ़्लो रद्द',
  },
  Konkani: {
    GetYourGroceries: 'ನಿಮ್ಮ ದಿನಸಿ ಸಾಮಾನುಗಳನ್ನು ನಮ್ಮೊಂದಿಗೆ ಪಡೆಯಿರಿ',
    ContinuePhone: 'ಫೋನ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ContinueGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    ContinueApple: 'Apple ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ErrorGoogleVerifyAccount: 'ನಿಮ್ಮ Google ಖಾತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    ErrorSignInProgress: 'ಸೈನ್ ಇನ್ ಪ್ರಗತಿಯಲ್ಲಿದೆ.....',
    ErrorGooglePlayServices: 'Google Play ಸೇವೆಗಳು ಲಭ್ಯವಿಲ್ಲ',
    ErrorCancelledSignInFlow: 'Google ಸೈನ್ ಇನ್ ಫ್ಲೋ ಅನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
  },
  Maithili: {
    GetYourGroceries: "हमरा सभक संग अपन किराना सामान ल' लिअ",
    ContinuePhone: 'फोन के साथ जारी रखें',
    ContinueGoogle: 'गूगल के संग आगू बढ़ू',
    ContinueApple: 'एप्पल के साथ जारी रखें',
    ErrorGoogleVerifyAccount: 'अपन गूगल खाता सत्यापित करू',
    ErrorSignInProgress: "साइन इन प्रगति क' रहल अछि.....",
    ErrorGooglePlayServices: 'गूगल प्ले सेवा उपलब्ध नहि अछि',
    ErrorCancelledSignInFlow: 'गूगल साइन इन प्रवाह रद्द कएल गेल',
  },
  Malayalam: {
    GetYourGroceries: 'നിങ്ങളുടെ പലചരക്ക് സാധനങ്ങൾ ഞങ്ങളോടൊപ്പം കൊണ്ടുവരിക',
    ContinuePhone: 'ഫോൺ ഉപയോഗിച്ച് തുടരുക',
    ContinueGoogle: 'Google-ൽ തുടരുക',
    ContinueApple: 'ആപ്പിളിനൊപ്പം തുടരുക',
    ErrorGoogleVerifyAccount: 'നിങ്ങളുടെ Google അക്കൗണ്ട് സ്ഥിരീകരിക്കുക',
    ErrorSignInProgress: 'സൈൻ ഇൻ പുരോഗമിക്കുന്നു.....',
    ErrorGooglePlayServices: 'Google Play സേവനങ്ങൾ ലഭ്യമല്ല',
    ErrorCancelledSignInFlow: 'Google സൈൻ ഇൻ ഫ്ലോ റദ്ദാക്കി',
  },
  Marathi: {
    GetYourGroceries: 'तुमचा किराणा सामान आमच्याकडे आणा',
    ContinuePhone: 'फोनसह सुरू ठेवा',
    ContinueGoogle: 'Google सह सुरू ठेवा',
    ContinueApple: 'Apple सह सुरू ठेवा',
    ErrorGoogleVerifyAccount: 'तुमचे Google खाते सत्यापित करा',
    ErrorSignInProgress: 'साइन इन प्रगती करत आहे.....',
    ErrorGooglePlayServices: 'Google Play Services उपलब्ध नाहीत',
    ErrorCancelledSignInFlow: 'Google साइन इन फ्लो रद्द केला',
  },
  Nepali: {
    GetYourGroceries: 'तपाईंको किराना सामानहरू हामीसँग पाउनुहोस्',
    ContinuePhone: 'फोनसँग जारी राख्नुहोस्',
    ContinueGoogle: 'Google को साथ जारी राख्नुहोस्',
    ContinueApple: 'एप्पलसँग जारी राख्नुहोस्',
    ErrorGoogleVerifyAccount: 'तपाईंको Google खाता प्रमाणित गर्नुहोस्',
    ErrorSignInProgress: 'साइन इन प्रगति हुँदैछ.....',
    ErrorGooglePlayServices: 'गुगल प्ले सेवाहरू उपलब्ध छैनन्',
    ErrorCancelledSignInFlow: 'Google साइन इन फ्लो रद्द गरियो',
  },
  Odia: {
    GetYourGroceries: 'ଆମ ସହିତ ଆପଣଙ୍କର ଖାଦ୍ୟ ସାମଗ୍ରୀ ପାଆନ୍ତୁ',
    ContinuePhone: 'ଫୋନ୍ ସହିତ ଜାରି ରଖନ୍ତୁ',
    ContinueGoogle: 'ଗୁଗୁଲ୍ ସହିତ ଜାରି ରଖ',
    ContinueApple: 'ଆପଲ୍ ସହିତ ଜାରି ରଖ',
    ErrorGoogleVerifyAccount: 'ଆପଣଙ୍କର ଗୁଗୁଲ୍ ଆକାଉଣ୍ଟ୍ ଯାଞ୍ଚ କରନ୍ତୁ',
    ErrorSignInProgress: 'ସାଇନ୍ ଇନ୍ ଅଗ୍ରଗତି କରୁଛି.....',
    ErrorGooglePlayServices: 'ଗୁଗୁଲ୍ ପ୍ଲେ ସେବା ଉପଲବ୍ଧ ନାହିଁ',
    ErrorCancelledSignInFlow: 'ଗୁଗୁଲ୍ ସାଇନ୍ ଇନ୍ ଫ୍ଲୋକୁ ବାତିଲ୍',
  },
  Punjabi: {
    GetYourGroceries: 'ਆਪਣਾ ਕਰਿਆਨਾ ਸਾਡੇ ਨਾਲ ਲਿਆਓ',
    ContinuePhone: 'ਫ਼ੋਨ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    ContinueGoogle: 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    ContinueApple: 'ਐਪਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    ErrorGoogleVerifyAccount: 'ਆਪਣੇ Google ਖਾਤੇ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    ErrorSignInProgress: 'ਸਾਈਨ ਇਨ ਤਰੱਕੀ ਹੋ ਰਹੀ ਹੈ.....',
    ErrorGooglePlayServices: 'Google Play ਸੇਵਾਵਾਂ ਉਪਲਬਧ ਨਹੀਂ ਹਨ',
    ErrorCancelledSignInFlow: 'Google ਸਾਈਨ ਇਨ ਫਲੋ ਨੂੰ ਰੱਦ ਕੀਤਾ',
  },
  Sanskrit: {
    GetYourGroceries: 'अस्माभिः सह किराणां सामानं प्राप्नुहि',
    ContinuePhone: 'फोनेन सह निरन्तरं कुर्वन्तु',
    ContinueGoogle: 'गुगलेन सह निरन्तरं कुर्वन्तु',
    ContinueApple: 'एप्पल् इत्यनेन सह निरन्तरं कुर्वन्तु',
    ErrorGoogleVerifyAccount: 'भवतः Google खातेः सत्यापनम्',
    ErrorSignInProgress: 'प्रवेशः प्रगतिशीलः अस्ति.....',
    ErrorGooglePlayServices: 'Google Play सेवाः उपलब्धाः न सन्ति',
    ErrorCancelledSignInFlow: 'गूगल-प्रवेश-प्रवाहः रद्दः',
  },
  Sindhi: {
    GetYourGroceries: 'اسان سان گڏ پنهنجو سامان حاصل ڪريو',
    ContinuePhone: 'فون سان جاري رکو',
    ContinueGoogle: 'گوگل سان جاري رکو',
    ContinueApple: 'ايپل سان جاري رکو',
    ErrorGoogleVerifyAccount: 'پنھنجي گوگل کاتي جي تصديق ڪريو',
    ErrorSignInProgress: 'سائن ان ٿي رهيو آهي.....',
    ErrorGooglePlayServices: 'Google Play خدمتون موجود نه آهن',
    ErrorCancelledSignInFlow: 'منسوخ ڪيو گوگل سائن ان فلو',
  },
  Tamil: {
    GetYourGroceries: 'உங்களின் மளிகை சாமான்களை எங்களுடன் பெற்றுக்கொள்ளுங்கள்',
    ContinuePhone: 'தொலைபேசியுடன் தொடரவும்',
    ContinueGoogle: 'Google உடன் தொடரவும்',
    ContinueApple: 'ஆப்பிளுடன் தொடரவும்',
    ErrorGoogleVerifyAccount: 'உங்கள் Google கணக்கைச் சரிபார்க்கவும்',
    ErrorSignInProgress: 'உள்நுழைவு நடைபெறுகிறது.....',
    ErrorGooglePlayServices: 'Google Play சேவைகள் கிடைக்கவில்லை',
    ErrorCancelledSignInFlow: 'Google உள்நுழைவு ஓட்டம் ரத்துசெய்யப்பட்டது',
  },
  Telugu: {
    GetYourGroceries: 'మీ కిరాణా సామాగ్రిని మాతో పొందండి',
    ContinuePhone: 'ఫోన్‌తో కొనసాగించండి',
    ContinueGoogle: 'Googleతో కొనసాగించండి',
    ContinueApple: 'Appleతో కొనసాగించండి',
    ErrorGoogleVerifyAccount: 'మీ Google ఖాతాను ధృవీకరించండి',
    ErrorSignInProgress: 'సైన్ ఇన్ ప్రోగ్రెస్‌లో ఉంది.....',
    ErrorGooglePlayServices: 'Google Play సేవలు అందుబాటులో లేవు',
    ErrorCancelledSignInFlow: 'Google సైన్ ఇన్ ఫ్లో రద్దు చేయబడింది',
  },
  Urdu: {
    GetYourGroceries: 'اپنا گروسری ہمارے ساتھ حاصل کریں۔',
    ContinuePhone: 'فون کے ساتھ جاری رکھیں',
    ContinueGoogle: 'گوگل کے ساتھ جاری رکھیں',
    ContinueApple: 'ایپل کے ساتھ جاری رکھیں',
    ErrorGoogleVerifyAccount: 'اپنے گوگل اکاؤنٹ کی تصدیق کریں۔',
    ErrorSignInProgress: 'سائن ان جاری ہے۔.....',
    ErrorGooglePlayServices: 'Google Play سروسز دستیاب نہیں ہیں۔',
    ErrorCancelledSignInFlow: 'Google سائن ان فلو کو منسوخ کر دیا گیا۔',
  },
};

export default LoginMainPageString;
