const LoginMainPageString = {
  Assamese: {
    GetYourGroceries: 'আমাৰ লগত আপোনাৰ গেলামালৰ বস্তু লৈ যাওক',
    ContinuePhone: 'Phone ৰ সৈতে আগবাঢ়ি যাওক',
    ContinueEmail: 'ইমেইলৰ সৈতে আগবাঢ়ি যাওক',
    ContinueGoogle: 'গুগলৰ সৈতে আগবাঢ়ি যাওক',
    ContinueApple: 'এপলৰ সৈতে আগবাঢ়ি যাওক',
    NotAccount: 'একাউণ্ট নাই নেকি?',
    SignUp: 'চাইনআপ কৰক',
  },
  Bengali: {
    GetYourGroceries: 'আমাদের সাথে আপনার মুদি পান',
    ContinuePhone: 'ফোন দিয়ে চালিয়ে যান',
    ContinueEmail: 'ইমেল দিয়ে চালিয়ে যান',
    ContinueGoogle: 'Google এর সাথে চালিয়ে যান',
    ContinueApple: 'অ্যাপলের সাথে চালিয়ে যান',
    NotAccount: 'একটি অ্যাকাউন্ট নেই?',
    SignUp: 'নিবন্ধন করুন',
  },
  Bodo: {
    GetYourGroceries: 'আমাদের সাথে আপনার মুদি পান',
    ContinuePhone: 'ফোন দিয়ে চালিয়ে যান',
    ContinueEmail: 'ইমেল দিয়ে চালিয়ে যান',
    ContinueGoogle: 'Google এর সাথে চালিয়ে যান',
    ContinueApple: 'অ্যাপলের সাথে চালিয়ে যান',
    NotAccount: 'একটি অ্যাকাউন্ট নেই?',
    SignUp: 'নিবন্ধন করুন',
  },
  Dogri: {
    GetYourGroceries: 'अपने किराने दा सामान साढ़े कन्ने लेई आओ',
    ContinuePhone: 'फोन दे नाल जारी रखो',
    ContinueEmail: 'ईमेल कन्नै जारी रक्खो',
    ContinueGoogle: 'गूगल दे कन्नै जारी रक्खो',
    ContinueApple: 'एप्पल दे कन्नै जारी रक्खो',
    NotAccount: 'खाता नहीं है ?',
    SignUp: 'साइनअप करो',
  },
  English: {
    GetYourGroceries: 'Get your groceries with us',
    ContinuePhone: 'Continue with Phone',
    ContinueEmail: 'Continue with Email',
    ContinueGoogle: 'Continue with Google',
    ContinueApple: 'Continue with Apple',
    NotAccount: "Don't have an account?",
    SignUp: 'SignUp',
  },
  Gujrati: {
    GetYourGroceries: 'તમારી કરિયાણા અમારી સાથે મેળવો',
    ContinuePhone: 'ફોન સાથે ચાલુ રાખો',
    ContinueEmail: 'ઇમેઇલ સાથે ચાલુ રાખો',
    ContinueGoogle: 'Google સાથે ચાલુ રાખો',
    ContinueApple: 'Apple સાથે ચાલુ રાખો',
    NotAccount: 'ખાતું નથી?',
    SignUp: 'સાઇન અપ કરો',
  },
  Hindi: {
    GetYourGroceries: 'अपने किराने का सामान हमारे साथ प्राप्त करें',
    ContinuePhone: 'फ़ोन के साथ जारी रखें',
    ContinueEmail: 'ईमेल के साथ जारी रखें',
    ContinueGoogle: 'Google के साथ जारी रखें',
    ContinueApple: 'सेब के साथ जारी रखें',
    NotAccount: 'खाता नहीं है?',
    SignUp: 'साइन अप करें',
  },
  Kannada: {
    GetYourGroceries: 'ನಿಮ್ಮ ದಿನಸಿ ಸಾಮಾನುಗಳನ್ನು ನಮ್ಮೊಂದಿಗೆ ಪಡೆಯಿರಿ',
    ContinuePhone: 'ಫೋನ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ContinueEmail: 'ಇಮೇಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ContinueGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    ContinueApple: 'Apple ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    NotAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    SignUp: 'ಸೈನ್ ಅಪ್',
  },
  Kashmiri: {
    GetYourGroceries: 'अपने किराने का सामान हमारे साथ प्राप्त करें',
    ContinuePhone: 'फ़ोन के साथ जारी रखें',
    ContinueEmail: 'ईमेल के साथ जारी रखें',
    ContinueGoogle: 'Google के साथ जारी रखें',
    ContinueApple: 'सेब के साथ जारी रखें',
    NotAccount: 'खाता नहीं है?',
    SignUp: 'साइन अप करें',
  },
  Konkani: {
    GetYourGroceries: 'ನಿಮ್ಮ ದಿನಸಿ ಸಾಮಾನುಗಳನ್ನು ನಮ್ಮೊಂದಿಗೆ ಪಡೆಯಿರಿ',
    ContinuePhone: 'ಫೋನ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ContinueEmail: 'ಇಮೇಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    ContinueGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    ContinueApple: 'Apple ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    NotAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    SignUp: 'ಸೈನ್ ಅಪ್',
  },
  Maithili: {
    GetYourGroceries: "हमरा सभक संग अपन किराना सामान ल' लिअ",
    ContinuePhone: 'फोन के साथ जारी रखें',
    ContinueEmail: 'ईमेल के साथ जारी रखें',
    ContinueGoogle: 'गूगल के संग आगू बढ़ू',
    ContinueApple: 'एप्पल के साथ जारी रखें',
    NotAccount: 'खाता नहि अछि ?',
    SignUp: 'साइनअप करू',
  },
  Malayalam: {
    GetYourGroceries: 'നിങ്ങളുടെ പലചരക്ക് സാധനങ്ങൾ ഞങ്ങളോടൊപ്പം കൊണ്ടുവരിക',
    ContinuePhone: 'ഫോൺ ഉപയോഗിച്ച് തുടരുക',
    ContinueEmail: 'ഇമെയിൽ ഉപയോഗിച്ച് തുടരുക',
    ContinueGoogle: 'Google-ൽ തുടരുക',
    ContinueApple: 'ആപ്പിളിനൊപ്പം തുടരുക',
    NotAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    SignUp: 'സൈൻ അപ്പ് ചെയ്യുക',
  },
  Marathi: {
    GetYourGroceries: 'तुमचा किराणा सामान आमच्याकडे आणा',
    ContinuePhone: 'फोनसह सुरू ठेवा',
    ContinueEmail: 'ईमेलसह सुरू ठेवा',
    ContinueGoogle: 'Google सह सुरू ठेवा',
    ContinueApple: 'Apple सह सुरू ठेवा',
    NotAccount: 'खाते नाही?',
    SignUp: 'साइनअप करा',
  },
  Nepali: {
    GetYourGroceries: 'तपाईंको किराना सामानहरू हामीसँग पाउनुहोस्',
    ContinuePhone: 'फोनसँग जारी राख्नुहोस्',
    ContinueEmail: 'इमेल जारी राख्नुहोस्',
    ContinueGoogle: 'Google को साथ जारी राख्नुहोस्',
    ContinueApple: 'एप्पलसँग जारी राख्नुहोस्',
    NotAccount: 'खाता छैन?',
    SignUp: 'साइनअप',
  },
  Odia: {
    GetYourGroceries: 'ଆମ ସହିତ ଆପଣଙ୍କର ଖାଦ୍ୟ ସାମଗ୍ରୀ ପାଆନ୍ତୁ',
    ContinuePhone: 'ଫୋନ୍ ସହିତ ଜାରି ରଖନ୍ତୁ',
    ContinueEmail: 'ଇମେଲ ସହିତ ଜାରି ରଖନ୍ତୁ',
    ContinueGoogle: 'ଗୁଗୁଲ୍ ସହିତ ଜାରି ରଖ',
    ContinueApple: 'ଆପଲ୍ ସହିତ ଜାରି ରଖ',
    NotAccount: 'ଏକ ଖାତା ନାହିଁ?',
    SignUp: 'ସାଇନ୍ ଅପ୍',
  },
  Punjabi: {
    GetYourGroceries: 'ਆਪਣਾ ਕਰਿਆਨਾ ਸਾਡੇ ਨਾਲ ਲਿਆਓ',
    ContinuePhone: 'ਫ਼ੋਨ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    ContinueEmail: 'ਈਮੇਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    ContinueGoogle: 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    ContinueApple: 'ਐਪਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    NotAccount: 'ਕੀ ਕੋਈ ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    SignUp: 'ਸਾਈਨਅੱਪ',
  },
  Sanskrit: {
    GetYourGroceries: 'अस्माभिः सह किराणां सामानं प्राप्नुहि',
    ContinuePhone: 'फोनेन सह निरन्तरं कुर्वन्तु',
    ContinueEmail: 'ईमेलेन सह निरन्तरं कुर्वन्तु',
    ContinueGoogle: 'गुगलेन सह निरन्तरं कुर्वन्तु',
    ContinueApple: 'एप्पल् इत्यनेन सह निरन्तरं कुर्वन्तु',
    NotAccount: 'खातं नास्ति वा?',
    SignUp: 'पञ्जीकरण',
  },
  Sindhi: {
    GetYourGroceries: 'اسان سان گڏ پنهنجو سامان حاصل ڪريو',
    ContinuePhone: 'فون سان جاري رکو',
    ContinueEmail: 'اي ميل سان جاري رکو',
    ContinueGoogle: 'گوگل سان جاري رکو',
    ContinueApple: 'ايپل سان جاري رکو',
    NotAccount: 'اڪائونٽ نه آهي؟',
    SignUp: 'سائن اپ ڪريو',
  },
  Tamil: {
    GetYourGroceries: 'உங்களின் மளிகை சாமான்களை எங்களுடன் பெற்றுக்கொள்ளுங்கள்',
    ContinuePhone: 'தொலைபேசியுடன் தொடரவும்',
    ContinueEmail: 'மின்னஞ்சலைத் தொடரவும்',
    ContinueGoogle: 'Google உடன் தொடரவும்',
    ContinueApple: 'ஆப்பிளுடன் தொடரவும்',
    NotAccount: 'கணக்கு இல்லையா?',
    SignUp: 'பதிவு செய்யவும்',
  },
  Telugu: {
    GetYourGroceries: 'మీ కిరాణా సామాగ్రిని మాతో పొందండి',
    ContinuePhone: 'ఫోన్‌తో కొనసాగించండి',
    ContinueEmail: 'ఇమెయిల్‌తో కొనసాగించండి',
    ContinueGoogle: 'Googleతో కొనసాగించండి',
    ContinueApple: 'Appleతో కొనసాగించండి',
    NotAccount: 'ఖాతా లేదా?',
    SignUp: 'చేరడం',
  },
  Urdu: {
    GetYourGroceries: 'اپنا گروسری ہمارے ساتھ حاصل کریں۔',
    ContinuePhone: 'فون کے ساتھ جاری رکھیں',
    ContinueEmail: 'ای میل کے ساتھ جاری رکھیں',
    ContinueGoogle: 'گوگل کے ساتھ جاری رکھیں',
    ContinueApple: 'ایپل کے ساتھ جاری رکھیں',
    NotAccount: 'اکاؤنٹ نہیں ہے؟',
    SignUp: 'سائن اپ',
  },
};

export default LoginMainPageString;
