const PhoneAuthenticationPageString = {
  Assamese: {
    EnterMobileNumber: 'আপোনাৰ মোবাইল নম্বৰ দিয়ক',
    SelectCountry: 'দেশ নিৰ্বাচন কৰ',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'নূন্যতম দৈৰ্ঘ্য ৪, সৰ্বোচ্চ দৈৰ্ঘ্য ১০',
    errorPhoneNumberResponse: 'অবৈধ ফোন নম্বৰ',
    enterOtp: 'OTP প্ৰৱেশ কৰক',
    otpPlaceholder: '000000',
    Continue: 'অব্যাহত ৰাখক',
    ErrorOtpVerifiedText: 'অবৈধ Otp',
  },
  Bengali: {
    EnterMobileNumber: 'আপনার মোবাইল নম্বর লিখুন',
    SelectCountry: 'দেশ নির্বাচন করুন',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'ন্যূনতম দৈর্ঘ্য 4, সর্বোচ্চ দৈর্ঘ্য 10',
    errorPhoneNumberResponse: 'অবৈধ ফোন নম্বর',
    enterOtp: 'ওটিপি লিখুন',
    otpPlaceholder: '000000',
    Continue: 'চালিয়ে যান',
    ErrorOtpVerifiedText: 'অবৈধ Otp',
  },
  Bodo: {
    EnterMobileNumber: 'আপনার মোবাইল নম্বর লিখুন',
    SelectCountry: 'দেশ নির্বাচন করুন',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'ন্যূনতম দৈর্ঘ্য 4, সর্বোচ্চ দৈর্ঘ্য 10',
    errorPhoneNumberResponse: 'অবৈধ ফোন নম্বর',
    enterOtp: 'ওটিপি লিখুন',
    otpPlaceholder: '000000',
    Continue: 'চালিয়ে যান',
    ErrorOtpVerifiedText: 'অবৈধ Otp',
  },
  Dogri: {
    EnterMobileNumber: 'अपना मोबाइल नंबर दर्ज करो',
    SelectCountry: 'देश चुनें',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'मिन लंबाई 4, मैक्स लंबाई 10',
    errorPhoneNumberResponse: 'अवैध फोन नंबरr',
    enterOtp: 'ओटीपी दर्ज करो',
    otpPlaceholder: '000000',
    Continue: 'जारी रखो',
    ErrorOtpVerifiedText: 'अवैध ओटीपी',
  },
  English: {
    EnterMobileNumber: 'Enter your Mobile Number',
    SelectCountry: 'Select Country',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'Min Length 4, Max Length 10',
    errorPhoneNumberResponse: 'Invalid Phone Number',
    enterOtp: 'Enter OTP',
    otpPlaceholder: '000000',
    Continue: 'Continue',
    ErrorOtpVerifiedText: 'Invalid Otp',
  },
  Gujrati: {
    EnterMobileNumber: 'તમારો મોબાઈલ નંબર દાખલ કરો',
    SelectCountry: 'દેશ પસંદ કરો',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'ન્યૂનતમ લંબાઈ 4, મહત્તમ લંબાઈ 10',
    errorPhoneNumberResponse: 'અમાન્ય ફોન નંબર',
    enterOtp: 'ટીપી દાખલ કરો',
    otpPlaceholder: '000000',
    Continue: 'ચાલુ રાખો',
    ErrorOtpVerifiedText: 'અમાન્ય Otp',
  },
  Hindi: {
    EnterMobileNumber: 'अपना मोबाइल नंबर दर्ज करें',
    SelectCountry: 'देश चुनें',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'न्यूनतम लंबाई 4, अधिकतम लंबाई 10',
    errorPhoneNumberResponse: 'अमान्य फ़ोन नंबर',
    enterOtp: 'ओटीपी दर्ज करें',
    otpPlaceholder: '000000',
    Continue: 'जारी रखें',
    ErrorOtpVerifiedText: 'अमान्य ओटीपी',
  },
  Kannada: {
    EnterMobileNumber: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    SelectCountry: 'ಸೆಲೆಕ್ಟ್ ಕಂಟ್ರಿ',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'ಕನಿಷ್ಟ ಉದ್ದ 4, ಗರಿಷ್ಠ ಉದ್ದ 10',
    errorPhoneNumberResponse: 'ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ',
    enterOtp: 'OTP ನಮೂದಿಸಿ',
    otpPlaceholder: '000000',
    Continue: 'ಮುಂದುವರಿಸಿ',
    ErrorOtpVerifiedText: 'ಅಮಾನ್ಯ Otp',
  },
  Kashmiri: {
    EnterMobileNumber: 'अपना मोबाइल नंबर दर्ज करें',
    SelectCountry: 'देश चुनें',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'न्यूनतम लंबाई 4, अधिकतम लंबाई 10',
    errorPhoneNumberResponse: 'अमान्य फ़ोन नंबर',
    enterOtp: 'ओटीपी दर्ज करें',
    otpPlaceholder: '000000',
    Continue: 'जारी रखें',
    ErrorOtpVerifiedText: 'अमान्य ओटीपी',
  },
  Konkani: {
    EnterMobileNumber: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    SelectCountry: 'ಸೆಲೆಕ್ಟ್ ಕಂಟ್ರಿ',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'ಕನಿಷ್ಟ ಉದ್ದ 4, ಗರಿಷ್ಠ ಉದ್ದ 10',
    errorPhoneNumberResponse: 'ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ',
    enterOtp: 'OTP ನಮೂದಿಸಿ',
    otpPlaceholder: '000000',
    Continue: 'ಮುಂದುವರಿಸಿ',
    ErrorOtpVerifiedText: 'ಅಮಾನ್ಯ Otp',
  },
  Maithili: {
    EnterMobileNumber: 'अपन मोबाइल नंबर दर्ज करू',
    SelectCountry: 'देश चुनें',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'मिन लंबाई 4, अधिकतम लंबाई 10',
    errorPhoneNumberResponse: 'अमान्य फोन नंबर',
    enterOtp: 'ओटीपी दर्ज करू',
    otpPlaceholder: '000000',
    Continue: 'आगाँ राखू',
    ErrorOtpVerifiedText: 'अमान्य Otp',
  },
  Malayalam: {
    EnterMobileNumber: 'നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക',
    SelectCountry: 'രാജ്യം തിരഞ്ഞെടുക്കുക',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'മിനിമം ദൈർഘ്യം 4, പരമാവധി നീളം 10',
    errorPhoneNumberResponse: 'അസാധുവായ ഫോൺ നമ്പർ',
    enterOtp: 'OTP നൽകുക',
    otpPlaceholder: '000000',
    Continue: 'തുടരുക',
    ErrorOtpVerifiedText: 'Otp അസാധുവാണ്',
  },
  Marathi: {
    EnterMobileNumber: 'तुमचा मोबाईल नंबर एंटर करा',
    SelectCountry: 'देश निवडा',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'किमान लांबी 4, कमाल लांबी 10',
    errorPhoneNumberResponse: 'अवैध फोन नंबर',
    enterOtp: 'OTP प्रविष्ट करा',
    otpPlaceholder: '000000',
    Continue: 'सुरू ठेवा',
    ErrorOtpVerifiedText: 'अवैध Otp',
  },
  Nepali: {
    EnterMobileNumber: 'तपाईंको मोबाइल नम्बर प्रविष्ट गर्नुहोस्',
    SelectCountry: 'देश चयन गर्नुहोस्',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'न्यूनतम लम्बाइ 4, अधिकतम लम्बाइ 10',
    errorPhoneNumberResponse: 'अवैध फोन नम्बर',
    enterOtp: 'OTP प्रविष्ट गर्नुहोस्',
    otpPlaceholder: '000000',
    Continue: 'जारी राख्नुहोस्',
    ErrorOtpVerifiedText: 'अवैध Otp',
  },
  Odia: {
    EnterMobileNumber: 'ଆପଣଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
    SelectCountry: 'ଦେଶ ଚୟନ',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'ମିନି ଲମ୍ବ 4, ସର୍ବାଧିକ ଲମ୍ବ 10',
    errorPhoneNumberResponse: 'ଅବ val ଧ ଫୋନ୍ ନମ୍ବର',
    enterOtp: 'OTP ପ୍ରବେଶ କର',
    otpPlaceholder: '000000',
    Continue: 'ଜାରି ରଖନ୍ତୁ',
    ErrorOtpVerifiedText: 'ଅବ val ଧ Otp',
  },
  Punjabi: {
    EnterMobileNumber: 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    SelectCountry: 'ਦੇਸ਼ ਚੁਣੋ',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'ਘੱਟੋ-ਘੱਟ ਲੰਬਾਈ 4, ਅਧਿਕਤਮ ਲੰਬਾਈ 10',
    errorPhoneNumberResponse: 'ਅਵੈਧ ਫ਼ੋਨ ਨੰਬਰ',
    enterOtp: 'ਓਟੀਪੀ ਦਾਖਲ ਕਰੋ',
    otpPlaceholder: '000000',
    Continue: 'ਜਾਰੀ ਰੱਖੋ',
    ErrorOtpVerifiedText: 'ਅਵੈਧ Otp',
  },
  Sanskrit: {
    EnterMobileNumber: 'भवतः मोबाईल नम्बरं प्रविशतु',
    SelectCountry: 'देशं चिनोतु',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'मिनट लंबाई ४, अधिकतम लम्बाई १०',
    errorPhoneNumberResponse: 'अमान्यः दूरभाषसङ्ख्या',
    enterOtp: 'OTP प्रविशतु',
    otpPlaceholder: '000000',
    Continue: 'अनुवर्तते',
    ErrorOtpVerifiedText: 'अमान्य Otp',
  },
  Sindhi: {
    EnterMobileNumber: 'پنهنجو موبائل نمبر داخل ڪريو',
    SelectCountry: 'ملڪ چونڊيو',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'گھٽ ۾ گھٽ ڊگھائي 4، وڌ ۾ وڌ ڊگھائي 10',
    errorPhoneNumberResponse: 'غلط فون نمبر',
    enterOtp: 'OTP داخل ڪريو',
    otpPlaceholder: '000000',
    Continue: 'جاري رکو',
    ErrorOtpVerifiedText: 'غلط Otp',
  },
  Tamil: {
    EnterMobileNumber: 'உங்களுடைய கைபேசி எண்ணை உள்ளிடவும்',
    SelectCountry: 'நாட்டினை தேர்வுசெய்',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'குறைந்தபட்ச நீளம் 4, அதிகபட்ச நீளம் 10',
    errorPhoneNumberResponse: 'தவறான தொலைபேசி எண்',
    enterOtp: 'OTP ஐ உள்ளிடவும்',
    otpPlaceholder: '000000',
    Continue: 'தொடரவும்',
    ErrorOtpVerifiedText: 'தவறான Otp',
  },
  Telugu: {
    EnterMobileNumber: 'మీ మొబైల్ నెంబర్ ను ఎంటర్ చేయండి',
    SelectCountry: 'దేశాన్ని ఎంచుకోండి',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'కనిష్ట పొడవు 4, గరిష్ట పొడవు 10',
    errorPhoneNumberResponse: 'చెల్లని ఫోన్ నంబర్',
    enterOtp: 'OTPని నమోదు చేయండి',
    otpPlaceholder: '000000',
    Continue: 'కొనసాగించు',
    ErrorOtpVerifiedText: 'చెల్లని Otp',
  },
  Urdu: {
    EnterMobileNumber: 'اپنا موبائل نمبر درج کیجئے',
    SelectCountry: 'ملک کا انتخاب کیجئے',
    phonePlaceholder: '0000000000',
    errorPhoneNumber: 'کم از کم لمبائی 4، زیادہ سے زیادہ لمبائی 10',
    errorPhoneNumberResponse: 'غلط فون نمبر',
    enterOtp: 'OTP درج کریں۔',
    otpPlaceholder: '000000',
    Continue: 'جاری رہے',
    ErrorOtpVerifiedText: 'غلط Otp',
  },
};

export default PhoneAuthenticationPageString;
